v4l2src: Fix compiler error in example caused by re-declaring `index`
 ../tests/examples/v4l2/v4l2src-renegotiate.c:57:13: error: ‘index’ redeclared as different kind of symbol
 static gint index = 0;
             ^