ci: Fix traceback when user doesn't have a cerbero fork
```
Traceback (most recent call last):
  File "ci/gitlab/trigger_cerbero_pipeline.py", line 59, in <module>
    if cerbero is None:
NameError: name 'cerbero' is not defined
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3063>