gstfilesink: fix the build with recent mingw-w64
The build fails with:
/clang64/include/unistd.h:59:5: error: conflicting types for '_chsize'
   59 | int ftruncate(int, off_t)

since ftruncate is redefined before unistd.h is included.

Avoid it by including the system headers first.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/10277>