git-update: Use --force when checking out manifest
When we have a manifest, we DEFINITELY want exactly that, please throw
away any local changes, thanks. Fixes CI:

https://gitlab.freedesktop.org/alatiera/gst-ci/-/jobs/3105690

```
 Checking out f5b44d31284cfa1b6d029fdfe69d6cdb9a8aeb36 in gst-devtools
Could not rebase subprojects\gst-devtools, please fix and try again. Error:
error: Your local changes to the following files would be overwritten by checkout:
	docs/plugins/fakesrc.simple.validatetest.yaml
Please commit your changes or stash them before you switch branches.
Aborting
 Command '['git', 'checkout', '--detach', 'f5b44d31284cfa1b6d029fdfe69d6cdb9a8aeb36']' returned non-zero exit status 1.
 ```

This is probably caused by some shared cache shenanigans, but forcing
is also what we want anyway in this case.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gst-build/-/merge_requests/162>