Revert "openjpegdec: support grayscale with alpha channel"
This reverts commit 1883ac26b7d02724c11d4f4bad8698c4873b443d.

This breaks the build on older versions of openjpeg:
gstopenjpegdec.c:752:30: error: ‘opj_image_comp_t {aka struct opj_image_comp}’ has no member named ‘alpha’

https://bugzilla.gnome.org/show_bug.cgi?id=783591