goom: fix build on PPC on openbsd
A missing sys/param.h include results in:

/usr/include/sys/proc.h:64: error: 'MAXLOGNAME' undeclared here (not in a
function)
/usr/include/sys/proc.h:285: error: 'MAXCOMLEN' undeclared here (not in a
function)

when compiling goom on openbsd/ppc. We can just remove the two sys/ includes
here, they are not needed for anything.

https://bugzilla.gnome.org/show_bug.cgi?id=654749