subprojects/libpng: Update to latest wrap file
It was getting pulled in automatically via cairo, but the version
there is too old for us. We need the latest to fix Windows ARM64 NEON
support:

> ERROR: No specified compiler can handle file subprojects\libpng-1.6.37\arm/filter_neon.S

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1570>