gst-examples/webrtc: fix error reported with android NDK 29
use of gpointer in place of guintptr is reported as error when compiled
with NDK 29 which was a previously reported as warning in NDK 25

Below is the error reported:
```
subprojects/gst-examples/webrtc/android/app/src/main/jni/webrtc.c:208:13:
error: incompatible pointer to integer conversion passing 'gpointer' (aka 'void *')
to parameter of type 'guintptr' (aka 'unsigned long') [-Wint-conversion]
    208 |             (gpointer) webrtc->native_window);
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/10821>