ci: fix fluster v4l2-statless on visl jobs in scheduled pipelines
This does not require gtk and fails with
ERROR: Dependency "gstreamer-gl-1.0" not found
at subprojects/gtk-4.14.5/modules/media/meson.build:10,
likely because the GStreamer OpenGL lib got disabled
via -Dauto_features=disabled.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/9676>