validate:launcher: Install config.py for non-development mode
Running installed gst-validate-launcher aborted with the following error.

File "lib/gst-validate-launcher/python/launcher/baseclasses.py", line 28, in <module>
  import config
ImportError: No module named config

This is because config.py is added but not installed
in ba6d209b3fd062f4e6bd889f81f1213cc12339ec.

https://bugzilla.gnome.org/show_bug.cgi?id=747087