docs: fix gst-docs build if opencv is not being built
The disabler in opencv_dep (retrieved via libs_doc) will
cause a meson interpreter error if opencv is not being built:

ERROR: The += operator currently only works with arrays, dicts, strings or ints
Part-of: <https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1519>