examples/gl/gtk: Add missing dependency on gstgl
Occasionally, a clean build would fail like this:

    In file included from ../subprojects/gst-plugins-base/tests/examples/gl/gtk/gstgtk.c:24:
    ../subprojects/gst-plugins-base/gst-libs/gst/gl/gl.h:25:10: fatal error: gst/gl/gl-enumtypes.h: No such file or directory
       25 | #include <gst/gl/gl-enumtypes.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~

Add the missing dependency so that the headers are generated beforehand.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/merge_requests/855>