benchmark: tracerserialize: add missing return statement
tracerserialize.c:117:1: error: control reaches end of
non-void function [-Werror=return-type]