ci: Fix documentation build on CI for 1.20 branch
Due to some interaction between the latest meson version and the
subproject cache on the image, the build fails:

  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 153, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msubprojects.py", line 679, in run
    results = loop.run_until_complete(asyncio.gather(*tasks))
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msubprojects.py", line 126, in run
    result = self.run_method()
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/msubprojects.py", line 411, in update
    self.wrap.update_hash_cache(self.wrap_resolver.dirname)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/wrap/wrap.py", line 228, in update_hash_cache
    with open(self.get_hashfile(subproject_directory), 'w', encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: './subprojects/pango-1.48.11/.meson-subproject-wrap-hash.txt'

https://gitlab.freedesktop.org/tpm/gstreamer/-/jobs/29467932

The error is in a different wrap each time. Restricting the meson
version to an older one fixes it, which is fine for a stable branch.

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/3139>