cairo.wrap: Bump to latest to fix MSYS2 build failure
```
../subprojects/cairo/src/win32/cairo-dwrite-font.cpp:722:50: error: 'MCW_PC' was not declared in this scope
  722 |         _controlfp_s(&control_word, _CW_DEFAULT, MCW_PC);
      |                                                  ^~~~~~
```

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/5018>