amrnbenc: remove global variables
gstcheck is declaring its own buffers glist which ends up
overwritten, loks like the code meant to use that already

gcc 10 is also complaining about this, but only on static
builds for some reason

```
FAILED: subprojects/gst-plugins-ugly/tests/check/elements_amrnbenc
/usr/bin/ld: subprojects/gstreamer/libs/gst/check/libgstcheck-1.0.a(gstcheck.c.o):(.bss+0x38): multiple definition of `buffers'; subprojects/gst-plugins-ugly/tests/check/708af1f@@elements_amrnbenc@exe/elements_amrnbenc.c.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
```

also remove unused var `current_buf`

Part-of: <https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly/-/merge_requests/62>